/* Autogenerated by png2wx.pl on Fri Jul  9 17:47:18 2010 */
#ifndef _COLTOP_BMP_H_
#define _COLTOP_BMP_H_ 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);
extern void uninitialize_images(void);

extern wxBitmap *_img_app_sml;
extern wxBitmap *_img_toolbar_pan;
extern wxBitmap *_img_toolbar_select;
extern wxBitmap *_img_toolbar_zoom;
extern wxBitmap *_img_toolbar_zoom_fit;
extern wxBitmap *_img_generic_export;
extern wxBitmap *_img_generic_quit;


#endif /* _COLTOP_BMP_H_ */
