/* Autogenerated by png2wx.pl on Fri Jul  9 17:47:18 2010 */
#ifndef _COLTOP_BMP_H_
#define _COLTOP_BMP_H_ 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);
extern void uninitialize_images(void);

extern wxBitmap *_img_app_sml;
extern wxBitmap *_img_toolbar_start_edit;

#endif /* _COLTOP_BMP_H_ */
